"""add coluna cpf em cliente

Revision ID: 8d770029d7d8
Revises: aa9899510630
Create Date: 2025-01-22 22:55:10.420402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d770029d7d8'
down_revision: Union[str, None] = 'aa9899510630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('cpf', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'cpf')
    # ### end Alembic commands ###
