"""data conclusao nullable

Revision ID: c0cf3ccc7d58
Revises: f377acc4f6ab
Create Date: 2025-01-22 01:44:41.617869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0cf3ccc7d58'
down_revision: Union[str, None] = 'f377acc4f6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
